title: Yan Wang # Website name
baseURL: 'https://yanwang-ai.github.io/' # Website URL
languageCode: en-us
defaultContentLanguage: en
hasCJKLanguage: true

enableGitInfo: false
enableRobotsTXT: true
disableKinds: [taxonomy, term, RSS]

outputs:
  home: [HTML]
  page: [HTML]
